google/googet

- build.cmd
- build.ps1
- build.sh
- googet.go
- googet.goospec
- googet_available.go
- googet_clean.go
- googet_download.go
- googet_install.go
- googet_installed.go
- googet_latest.go
- googet_remove.go
- googet_update.go
- goopack/goopack.go
The clean subcommand removes all files and folders in the cache directory that don't correspond with a currently installed package.
Build script on windows is now PowerShell
Both windows and Linux build scripts pull version out of goospec file.
> Add clean subcommand and a few other things

- oswrap/oswrap.go
- oswrap/oswrap_test.go
fix oswrap.MkdirAll bug when trying to create directory only one level deep
> fix oswrap.MkdirAll bug

- googet.goospec
- system/system_windows.go
Both msu and exe files are known to use msi success codes when restarts
are required (i.e. the .net redist). Ensure these files correctly report
success to googet when installing/removing.
> Expand usage of msi success codes.

- googet.goospec
- goolib/goospec.go
- goolib/goospec_test.go
Trimming leading zeros failed to take pre-release/build metadata into
account in the patch component and resulted in failed parsing of valid
version strings.
> Fix semver patch metadata handling.

- download/download.go
- googet.go
- googet.goospec
- googet_test.go
- goolib/goospec.go
- goolib/goospec_test.go
- install/install.go
Add allowunsafeurl config option to enable HTTP repos, otherwise disable
Force the use of a package checksum when downloading from a repository
Style fixes
> Set secure defaults when downloading from a repo

- googet.goospec
- googet_clean.go
- googet_test.go
- goolib/goolib.go
- goolib/goospec.go
- goolib/goospec_test.go
- install/install.go
- remove/remove.go
- remove/remove_test.go
- system/system_linux.go
- system/system_windows.go
Package Conflicts will prevent the package from being installed if a conflicting package is already installed
Package Replaces will remove any packages that are replaced by one being installed
> Add Conflicts and Replaces to the PkgSpec

- googet.go
'AllowUnsafeURL' in googet.conf doesn't work because
go-yaml/yaml's Unmarshal() expects keys to be all
lowercase. The error message about unsafe repos was
therefore misleading. This change informs the user
of the correct key to put in googet.conf.
> Use correct case for 'allowunsafeurl' in error

- server/gooserve.go
Code previously put the local filesystem path rather than the path
relative to the web server root into the 'Source' attribute of the
metadata JSON.
> Corrected 'Source' path in packages with -root

- server/gooserve.go
The client disallows http (no 's') by default but the server only
serves http. The server is therefore likely to be configured
behind a revers proxy. A defense-in-depth approach involves
having such services listen only on localhost. This change makes
the address the server listens on configurable to support such a
configuration.
> Made listening address configurable

- README.md
- download/download.go
- googet.goospec
- server/README.md
* path.Dir() failed to strip the repo name if the repo URL
contained a trailing slash.
* Updated GCS repo documentation to include a repo name in the
path.
> Fixed issue with trailing slash in repo paths

- client/client.go
- client/client_test.go
- googet.goospec
- goolib/goospec.go
* Closes #47
* Use sha256 sum of repo URL for cache file name instead of last
path component to ensure (mostly) that two distinct repos never
use the same cache file.
I opted for a hash rather than replacing / with _ because we'd have the same problem with http://pkgs.com/my/repo and http://pkgs.com/my_repo.
> Ensure unique cache file for each repo

- download/download.go
- googet.goospec
- remove/remove.go
Avoid having remove package attempt to operate on empty path strings if package state goes missing.
> Mitigations for undefined LocalPath in package states

- googet.goospec
- googet_installed.go
The '-files' flag allows you to easily see the directly-managed list of files for a particular GooGet package or all of them. Great for quickly figuring out which package may contain a particular file. Outputs a message if no directly-managed files are found.
> Add flag to 'googet installed' to list directly-managed files.

- .travis.win_integration_test.ps1
- .travis.yml
- README.md
- googet.goospec
- goolib/goospec_test.go
- goopack/goopack.go
- goopack/goopack_test.go
- install/install_test.go
- oswrap/oswrap.go
- oswrap/oswrap_test.go
Updated goospec to build under windows
Added travis-ci config to test under linux (trusty) and windows
Added logic to only run gofmt under linux (git messes with line endings and gofmt doesn't like that)
Added logic to build, install, and remove googet when running under windows
Updated build documentation
https://travis-ci.org/GitGerby/googet/builds/556570294
certain unit tests fail under Windows at the moment
> add config for windows tests in travis-ci

- download/download.go
- googet.goospec
- verify/verify.go
The download and verify subcommands are failing to check the server response for non-successful status codes. This can lead to files being written containing the contents of an error page rather than the expected file content.
Fixes #72
> Add a status code check for HTTP responses.

- googet.go
- googet.goospec
- lock_linux.go
- lock_windows.go
* Use the rootDir flag in the path to GooGet's lock file, to avoid assuming that it will be located on C:\
> Update path to lock file

- googet.goospec
- system/system_windows.go
Removing error message as it is called before logging has been initialized and updating package version.
> Removing error message in x86 detection 

- googet.goospec
- googet_rmrepo.go
Addresses static check error SA6005: https://staticcheck.io/docs/checks#SA6005
> Use strings.EqualFold for efficient string comparison.

- README.md
- client/client.go
- download/download.go
- go.mod
- googet.go
- googet_test.go
Support for passing Oauth headers via the google Oauth library. Repositories are configured for oauth by adding an "oauth" line to their repo file. For example:
```
URL: https://foo.com/googet/bar
oauth: true
``` 
cc @adjackura
> Add Google Oauth support

- googet.goospec
- verify/verify.go
- verify/verify_test.go
This PR addresses the `googet verify` failure message which the verify should pass. Please also refer to internal bug.
The `googet verify` compares the checksums between
- the file checksum information within the googet state file, and
- calculated checksum of current file(s) on disk
As the googet state file only keep file checksum, and not folder. This PR ensures verify only checks for file checksum.
The `go test` result is `PASS`. Summarized result:
```
> go test  -v
=== RUN   TestFiles
Running file verification for foo.noarch.1.0.0@1...
<...log truncated...>
--- PASS: TestFiles (0.03s)
PASS
ok      github.com/google/googet/v2/verify      1.171s
```
Thank you,
Lawrence
> Bugfix googet verify

- .github/workflows/go.yml
- go.mod
- oswrap/oswrap_unix.go
- oswrap/oswrap_windows.go
- system/system_linux.go
- system/system_windows.go
Update go.mod for googet to Go 1.16.
- Update go.mod to 1.16
- Update Github workflows as well
- Run gofmt as needed for workflows to pass
> update go.mod to 1.16

- googet.goospec
Results in JSON syntax error if this is not present when attempting to build from source.
> Update goospec releaseNotes JSON syntax

- googet.goospec
- system/system_windows.go
write install date to registry to allow tools like osquery to determine when a goo package was installed.
> add installdate metadata

- go.mod
- go.sum
- system/system_windows.go
The github.com/StackExchange/wmi project has been archived. Replace it with the recommended fork at github.com/yusufpapurcu/wmi.
> Replace the archived StackExchange/wmi dependency

- client/client.go
- googet.go
- googet_test.go
- googet_update.go
- goolib/goospec.go
- goolib/goospec_test.go
- priority/priority.go
- priority/priority_test.go
This maps certain strings like "rollback" or "canary" to a standard integer priority so that priorities in repo configs may be specified with these strings.
> Allow using semantic names for priority levels.

- googet.go
- googet_addrepo.go
- googet_test.go
- priority/priority.go
Don't write priority field in repo config if not specified.
Unspecified priorities are always interpreted as the default value.
Marshal priority values with semantic names when appropriate.
Add tests for writeRepoFile.
Looks like:
```
% googet -root=/tmp addrepo --file temp.repo foo https://googet.server.com/foo     
Wrote repo file /tmp/repos/temp.repo with content:
- name: foo
url: https://googet.server.com/foo
useoauth: false
% googet -root=/tmp addrepo --file temp.repo --priority rollback bar https://googet.server.com/bar     
Appended to repo file /tmp/repos/temp.repo with the following content:
- name: bar
url: https://googet.server.com/bar
useoauth: false
priority: rollback
% cat /tmp/repos/temp.repo 
- name: foo
url: https://googet.server.com/foo
useoauth: false
- name: bar
url: …
```
> Add support for specifying the priority with addrepo subcommand

- system/system_windows.go
Windows adds registry keys for uninstalls. If uninstall args are not specified, use the uninstall string from the registry. Currently targeting MSI but leaving room for other formats.
> Uninstall without uninstall args

- system/system_windows.go
Pull display name to compare with package name, remove whitespace from display name. 
Fix logic to search uninstall string if silent string does not exist.
> update exe uninstall to be more reliable

- system/system_windows.go
Add support for msixbundles and apps. Install for all users using Add/Remove-AppxProvisisionedPackage.
> Add support for msix installers

- system/system.go
- system/system_windows.go
Mimic winget uninstall feature by implementing regex that Microsoft uses. This makes uninstalls for applications with no uninstall directive more reliable.
> Improve uninstall workflow

- googet.goospec
arm64 support was previously added in https://github.com/google/googet/pull/128
> Bump version and update changelog for arm64 support.

- client/client.go
- client/client_test.go
- download/download.go
- googet_available.go
- googet_download.go
- googet_install.go
- googet_latest.go
- googet_remove.go
- googet_update.go
- googet_verify.go
- install/install.go
- remove/remove.go
- remove/remove_test.go
- verify/verify.go
Before: Almost every HTTP GET request went through client.Get, which created a new http.Transport (inside of http.DefaultClient) for each request. The code in verify.Command created its own http.Client separately from client.Get.
After: googet creates a single http.Client via NewDownloader, which is reused for all requests, per https://pkg.go.dev/net/http#hdr-Clients_and_Transports. The downloader is passed through to anything that needs it (in place of the proxyServer URL that was formerly being passed around). verify.Command uses this same downloader.
> Reuse the same HTTP client for all requests.

- googet.go
- googet_installed.go
- Move lock request to before we create the DB to make sure that we aren't exiting with an empty database if lock can't be obtained.
- Add failsafe in googet installed where if db is empty and a state file exists we can try the re-conversion again
> Request googet lock before creating DB

- download/download.go
- googet_download.go
- install/install.go
Instead of "https://my-googet-server/repos/../packages/my.goo", store "http://my-googet-server/packages/my.goo".
This returns the resolved package URL from download.FromRepo and download.Latest.
Also simplify the code for resolving the package URL by using url.JoinPath.
> Clean the package download URLs before storing them in PackageState.

- googet_check.go
- googetdb/googetdb.go
- system/system_linux.go
- system/system_windows.go
- Make appassociation accept pkgspec so we can do all association logic there(instead of in check and db code)
- Check for publisher matches on smaller applications
- Omit any package with "Files". This typically denotes portable apps that do not have installers.
> Fix detection logic for smaller package names

- download/download.go
If the tarfile contains a filename with len < 3, this panics.
Fixes #155.
> Don't panic when checking short filenames for path traversal.

- .github/workflows/go.yml
- googet_install.go
- googet_install_test.go
- googetdb/googetdb.go
This moves most of the googet_install code out of Execute so that it can be tested. More of a first step towards refactoring than final end state, since googet_install.go should not be part of the main package and I'm not certain any of the installer code actually belongs here.
Adds an end-to-end integration test for installing packages which tests finding, downloading, extracting, installing, and modifying the database package state. Will add more test cases in future PRs.
> Refactor googet_install and add integration tests

- googet_install.go
- googet_install_test.go
Pull the full package state when doing installs so that we have info on whether or not dependent packages are already installed and so can avoid reinstalling them.
For installs with the `--reinstall` flag, this preserves the existing behavior where only the named package is reinstalled, and dependent packages are ignored. Thus, when `--reinstall` is specified, we still only need package state for the named package.
> Don't reinstall already-installed dependencies.

- googet_clean.go
- googet_test.go
Removes the dependency on readState (defined in googet.go) from googet_clean. Grab the state from db.FetchPkgs for cleanOld. Rename cleanPackages, clean, cleanOld to be more descriptive. Use a map for more efficient inclusion tests instead of iterating over a slice in an inner loop.
> Don't use obsolete state file in googet_clean.

- client/client.go
- googet.go
- googet_installed.go
- googetdb/googetdb.go
- googetdb/googetdb_test.go
* Move all of the conversion code into CreateIfMissing function in googetdb.
* Move readState out of package main and into googetdb.
* Delete the unused writeState function.
* In googet.go, always obtain lock before attempting conversion. If database already exists, allow "googet installed" to run. Otherwise "googet installed" will grab a lock and try to convert the state file into a database.
* Move conversion to after logging has been setup so that we can properly log errors.
* In addPkg, update the InstallDate to the current time only if it is the zero value. This allows us to preserve install dates from existing state files that are converted. But, more importantly, also means that we preserve install dates when we read the entire package state and then write it back out.
> Move state file to db conversion code into googetdb.

- googet.go
- googet_available.go
- googet_installed.go
- goolib/goospec.go
- goolib/goospec_test.go
The info() function in googet.go is used by the "installed" and "available" subcommands to print out info about a PkgSpec. This moves that code into the goolib package, next to the PkgSpec definition. Cleaned it up, made it a method on PkgSpec, and renamed it to PrettyPrint. Added tests. The only difference in the old output vs the new output is that listed dependencies are now printed in a deterministic order.
> Move info function from package main into goolib.

- go.mod
- googet_check.go
- googet_install.go
- googet_install_test.go
- googet_remove.go
- googet_update.go
- googet_verify.go
- googetdb/googetdb.go
- install/install.go
- install/install_test.go
- remove/remove.go
- remove/remove_test.go
- Remove the passing of state in favor of passing the db object
- Add/Remove packages as they finish uninstalling, rather than batch at the end
- This fixes replaces logic since we aren't just slamming a new state file every time.
> Fix replaces logic and moves db actions to more timely execution

- go.mod
- googet.go
- googet_test.go
- lock_linux.go
- lock_windows.go
This changes obtainLock (and the underlying platform-specific lock functions) to return a cleanup function, rather than having them add the cleanup to a global deferredFuncs variable. The returned cleanup function is deferred using normal Go idioms. As part of this change, we move most of the code of main into a separate run function and call os.Exit in at most one place in order to ensure that deferred funcs are run before the program exits. This also means converting logger.Fatal calls to logger.Error instead, since logger.Fatal immediately calls os.Exit, circumventing any defers.
> Get rid of the global deferredFuncs variable.

- cli/check/check.go
Googet check is incorrectly setting the exit code to 1 even in successful runs, this should allow it to exit 0.
> Correct `googet check` exit code

- cli/available/available.go
- cli/check/check.go
- cli/clean/clean.go
- cli/download/download.go
- cli/install/install.go
- cli/installed/installed.go
- cli/latest/latest.go
- cli/listrepos/listrepos.go
- cli/update/update.go
- cli/verify/verify.go
Get rid of most occurrences of logger.Fatal. These are bad because they immediately call `os.Exit(1)`, bypassing any clean up code (for example lock cleanup) that would have otherwise been executed before program exit.
> Replace logger.Fatal with logger.Error + return subcommands.ExitFailure
